name: smart_barcode_reader
description: A Flutter package for intelligently detecting and processing barcode scanner inputs, supporting formats like EAN-13 with adaptive speed and length validation.
version: 0.0.2+4
homepage: https://github.com/MR-4-Code/smart_barcode_reader
repository: https://github.com/MR-4-Code/smart_barcode_reader
issue_tracker: https://github.com/MR-4-Code/smart_barcode_reader/issues

environment:
  sdk: ^3.10.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
